name = "frontend"
compatibility_date = "2024-06-17"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = ".vercel/output/static"

[[build.upload]]
format = "service-worker"