name = "backend"
main = "worker.py"
compatibility_date = "2024-06-17"

[build]
command = "pip install -r requirements.txt -t ."

[[kv_namespaces]]
binding = "KV"
id = "your-kv-namespace-id"

[env.production]
vars = { ENVIRONMENT = "production" }